# Generated by Django 6.1 on 2026-09-14 13:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mahasiswa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('tipe', models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile App'), ('game', 'Game Development'), ('data', 'Data Science'), ('other', 'Other')], default='web', max_length=20)),
                ('deskripsi', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('skillset', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='thumbnail',
            field=models.CharField(max_length=255),
        ),
    ]
