# Generated by Django 6.1 on 2026-09-21 13:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_alter_experience_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.CharField(max_length=255),
        ),
    ]
