# Generated by Django 6.1 on 2026-10-05 05:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_starred_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='loved_by',
            field=models.ManyToManyField(blank=True, related_name='loved_arts', to=settings.AUTH_USER_MODEL),
        ),
    ]
